AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
Style/Documentation:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
