#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'menu'
require_relative './sources/azlyrics'
require_relative './sources/genius'
require_relative './sources/lyricsfreak'

class LyricsTo
  attr_reader :artist, :song

  def initialize(artist:, song:)
    @artist = artist
    @song = song
  end

  def azlyrics
    Sources::AZLyrics.new(artist: artist, song: song).fetch_lyrics
  end

  def lyricsfreak
    Sources::LyricsFreak.new(artist: artist, song: song).fetch_lyrics
  end

  def genius
    Sources::Genius.new(artist: artist, song: song).fetch_song_url
  end
end

opts = Menu.new(artist: ARGV[0], song: ARGV[1]).create

lyrics_to = LyricsTo.new(artist: opts['a'], song: opts['s'])

if opts['d']
  lyrics_to.genius
  exit 0
end

if opts['z']
  lyrics_to.azlyrics
elsif opts['f']
  lyrics_to.lyricsfreak
end
